import dialogs.browser
import dialogs.power
import dialogs.delay
import dialogs.mouseabsolute
import dialogs.mouserelative
import dialogs.power
import dialogs.process
import dialogs.schedule
import dialogs.window